version: 2
updates:
  - package-ecosystem: pip
    directory: /services/ingestion
    schedule:
      interval: weekly
  - package-ecosystem: pip
    directory: /services/stream-processor
    schedule:
      interval: weekly
  - package-ecosystem: pip
    directory: /services/anomaly-detector
    schedule:
      interval: weekly
  - package-ecosystem: pip
    directory: /services/alert-service
    schedule:
      interval: weekly
  - package-ecosystem: pip
    directory: /services/api
    schedule:
      interval: weekly
  - package-ecosystem: pip
    directory: /simulator
    schedule:
      interval: weekly
  - package-ecosystem: pip
    directory: /scripts/seed
    schedule:
      interval: weekly
  - package-ecosystem: pip
    directory: /tests
    schedule:
      interval: weekly

  - package-ecosystem: npm
    directory: /frontend
    schedule:
      interval: weekly
    groups:
      npm-dependencies:
        patterns: ["*"]

  - package-ecosystem: github-actions
    directory: /
    schedule:
      interval: weekly

  - package-ecosystem: docker
    directory: /frontend
    schedule:
      interval: weekly
  - package-ecosystem: docker
    directory: /infrastructure/docker/migrate
    schedule:
      interval: weekly
  - package-ecosystem: docker
    directory: /scripts/seed
    schedule:
      interval: weekly
  - package-ecosystem: docker
    directory: /services/alert-service
    schedule:
      interval: weekly
  - package-ecosystem: docker
    directory: /services/anomaly-detector
    schedule:
      interval: weekly
  - package-ecosystem: docker
    directory: /services/api
    schedule:
      interval: weekly
  - package-ecosystem: docker
    directory: /services/ingestion
    schedule:
      interval: weekly
  - package-ecosystem: docker
    directory: /services/stream-processor
    schedule:
      interval: weekly
  - package-ecosystem: docker
    directory: /simulator
    schedule:
      interval: weekly
